### ISSUE TITLE
System doesn't yet work "out of the box"

### ISSUE THREAD

**Issue by RichardBruskiewich** [galaxy-genome-annotation/dockerized-gmod-deployment#12]
By applying the proposed pull request patch inspired by Issue #10 , the docker-compose build can be made to complete to running a swarm of containers, but one strongly suspects that the docker-compose.yml container ports are not yet properly set to access each of the resulting web components. If I figure out what is going on, I'll update this issue report...but hopefully, somebody else more on top of this complex project will sort things out.

The only component that properly works is the **pgadmin** docker web container. I notice that this the **pgadmin** container is the only one for which proper explicit port mappings are really specified inside the _docker-compose.yml_ file. 

Here's what _docker ps_ reports:

```
$ docker ps
CONTAINER ID        IMAGE                                                              COMMAND                   CREATED             STATUS              PORTS                                         NAMES
b62a4a779413        quay.io/erasche/gx-cookie-proxy:latest                             "/usr/bin/gx-cookie-…"    3 hours ago         Up 3 hours          5000/tcp                                      dockerized-gmod-deployment_remoteuser_1
6e3690e97e6e        quay.io/erasche/apollo:remote_user                                 "/bin/sh -c \"/launch…"   3 hours ago         Up 3 hours          8080/tcp                                      dockerized-gmod-deployment_apollo_1
ad7ad5ec8aaa        quay.io/galaxy-genome-annotation/jbrowse:v1.12.5                   "/docker-entrypoint.…"    3 hours ago         Up 3 hours          80/tcp                                        dockerized-gmod-deployment_jbrowse_1
07741da2ecac        thajeztah/pgadmin4                                                 "python ./usr/local/…"    3 hours ago         Up 3 hours          0.0.0.0:8201->5050/tcp                        dockerized-gmod-deployment_pgadmin4_1
4b1d06df6370        quay.io/erasche/postgrest:latest                                   "/bin/sh -c /run.sh"      3 hours ago         Up 3 hours          3000/tcp                                      dockerized-gmod-deployment_postgrest_1
781c7d3144dd        quay.io/erasche/chado-jbrowse-connector:latest                     "bash /go/src/github…"    3 hours ago         Up 3 hours                                                        dockerized-gmod-deployment_chado_jb_1
32259a8f98df        erasche/postgraphql:gmod-hacks                                     "/run.sh"                 3 hours ago         Up 3 hours          5000/tcp                                      dockerized-gmod-deployment_postgraphql_1
bc70bbf95a03        quay.io/galaxy-genome-annotation/docker-galaxy-annotation:master   "/usr/bin/startup"        3 hours ago         Up 3 hours          21/tcp, 80/tcp, 443/tcp, 8800/tcp, 9002/tcp   dockerized-gmod-deployment_galaxy_1
0ca845a1a3dd        quay.io/galaxy-genome-annotation/jbrowse:v1.12.5                   "/docker-entrypoint.…"    3 hours ago         Up 3 hours          80/tcp                                        dockerized-gmod-deployment_jbrowse-graphql_1
2db572cc32ec        quay.io/galaxy-genome-annotation/tripal:latest                     "/usr/local/bin/tini…"    3 hours ago         Up 3 hours          80/tcp                                        dockerized-gmod-deployment_tripal_1
39269fa808e1        docker.elastic.co/elasticsearch/elasticsearch:6.4.2                "/usr/local/bin/dock…"    3 hours ago         Up 3 hours          9200/tcp, 9300/tcp                            dockerized-gmod-deployment_elasticsearch_1
a5d86f7aeda0        quay.io/galaxy-genome-annotation/chado:1.31-jenkins97-pg9.5        "docker-entrypoint.s…"    3 hours ago         Up 3 hours          5432/tcp                                      dockerized-gmod-deployment_tripal_db_1
e3ddcf29c594        postgres:9.5                                                       "docker-entrypoint.s…"    3 hours ago         Up 3 hours          5432/tcp                                      dockerized-gmod-deployment_apollo_db_1
```

Hmm.. and some key containers exited  prematurely: _docker ps -A_ also reports:

```
CONTAINER ID        IMAGE                                                              COMMAND                   CREATED             STATUS                   PORTS                                         NAMES
5786313b0729        nginx:latest   "nginx -g 'daemon of…"    3 hours ago         Exited (1) 3 hours ago                dockerized-gmod-deployment_proxy_1
...
8466b42aab83        dockerized-gmod-deployment_postgraphql-refseqs                     "/usr/local/bin/guni…"    3 hours ago   Exited (3) 3 hours ago  
dockerized-gmod-deployment_postgraphql-refseqs_1
```

Interesting, trying to start the nginx up again (using docker-compose) generates the following error:

```
proxy_1                | 2018/12/03 01:04:06 [emerg] 1#1: host not found in upstream "postgraphql-refseqs" in /etc/nginx/conf.d/default.conf:133
proxy_1                | nginx: [emerg] host not found in upstream "postgraphql-refseqs" in /etc/nginx/conf.d/default.conf:133
dockerized-gmod-deployment_proxy_1 exited with code 1
```

hmm.... Digging a bit deeper by attempting to restart "postgraphql-refseqs" gives:

```
$ docker-compose -f docker-compose-fixed.yml up postgraphql-refseqs
dockerized-gmod-deployment_tripal_db_1 is up-to-date
Starting dockerized-gmod-deployment_postgraphql-refseqs_1 ... done
Attaching to dockerized-gmod-deployment_postgraphql-refseqs_1
postgraphql-refseqs_1  | [2018-12-03 01:05:47 +0000] [1] [INFO] Starting gunicorn 19.9.0
postgraphql-refseqs_1  | [2018-12-03 01:05:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
postgraphql-refseqs_1  | [2018-12-03 01:05:47 +0000] [1] [INFO] Using worker: sync
postgraphql-refseqs_1  | [2018-12-03 01:05:47 +0000] [14] [INFO] Booting worker with pid: 14
postgraphql-refseqs_1  | [2018-12-03 01:05:48 +0000] [14] [ERROR] Exception in worker process
postgraphql-refseqs_1  | Traceback (most recent call last):
postgraphql-refseqs_1  |   File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
postgraphql-refseqs_1  |     worker.init_process()
postgraphql-refseqs_1  |   File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
postgraphql-refseqs_1  |     self.load_wsgi()
postgraphql-refseqs_1  |   File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
postgraphql-refseqs_1  |     self.wsgi = self.app.wsgi()
postgraphql-refseqs_1  |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
postgraphql-refseqs_1  |     self.callable = self.load()
postgraphql-refseqs_1  |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
postgraphql-refseqs_1  |     return self.load_wsgiapp()
postgraphql-refseqs_1  |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
postgraphql-refseqs_1  |     return util.import_app(self.app_uri)
postgraphql-refseqs_1  |   File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
postgraphql-refseqs_1  |     __import__(module)
postgraphql-refseqs_1  |   File "/deploy/app/hello.py", line 3, in <module>
postgraphql-refseqs_1  |     from flask.ext.sqlalchemy import SQLAlchemy
**postgraphql-refseqs_1  | ImportError: No module named ext.sqlalchemy**
postgraphql-refseqs_1  | [2018-12-03 01:05:48 +0000] [14] [INFO] Worker exiting (pid: 14)
postgraphql-refseqs_1  | [2018-12-03 01:05:48 +0000] [1] [INFO] Shutting down: Master
postgraphql-refseqs_1  | [2018-12-03 01:05:48 +0000] [1] [INFO] Reason: Worker failed to boot.
dockerized-gmod-deployment_postgraphql-refseqs_1 exited with code 3
```

Missing python module pip requirement somewhere in postgraphql-refseqs?

**Comment by hexylena** [comment]
> running a swarm of containers

never tested this under swarm, no comments to rest yet, it is not a good month. maybe @abretaud has some comments

**Comment by hexylena** [comment]
Yeah, looks like that @ postgraphql-refseqs. Can you rebuild that container?

```
docker-compose -f docker-compose-fixed.yml build postgraphql-refseqs
```

The [dockerfile](https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment/blob/master/refseqs/Dockerfile#L10) installs [app/requirements.txt](https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment/blob/master/refseqs/app/requirements.txt) which includes flask-sqlalchemy, so maybe something went wrong during installation or?

**Comment by abretaud** [comment]
I'll look into it, the error looks like a version problem with the flask module, I had something like this on another app, shouldn't be too hard

**Comment by abretaud** [comment]
I've made this PR which should fix the postgraph-refseqs error: https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment/pull/13

I still have an error with pgadmin4:

```
pgadmin4_1             | Traceback (most recent call last):
pgadmin4_1             |   File "./usr/local/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py", line 70, in <module>
pgadmin4_1             |     app = create_app()
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/pgadmin4/pgadmin/__init__.py", line 315, in create_app
pgadmin4_1             |     db_upgrade(app)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/pgadmin4/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
pgadmin4_1             |     flask_migrate.upgrade(migration_folder)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
pgadmin4_1             |     command.upgrade(config, revision, sql=sql, tag=tag)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
pgadmin4_1             |     script.run_env()
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
pgadmin4_1             |     util.load_python_file(self.dir, 'env.py')
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
pgadmin4_1             |     module = load_module_py(module_id, path)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
pgadmin4_1             |     mod = imp.load_source(module_id, path, fp)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/pgadmin4/pgadmin/setup/../../migrations/env.py", line 94, in <module>
pgadmin4_1             |     run_migrations_online()
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/pgadmin4/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
pgadmin4_1             |     context.run_migrations()
pgadmin4_1             |   File "<string>", line 8, in run_migrations
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
pgadmin4_1             |     self.get_context().run_migrations(**kw)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 314, in run_migrations
pgadmin4_1             |     self._ensure_version_table()
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 265, in _ensure_version_table
pgadmin4_1             |     self._version.create(self.connection, checkfirst=True)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 778, in create
pgadmin4_1             |     checkfirst=checkfirst)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
pgadmin4_1             |     **kwargs).traverse_single(element)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
pgadmin4_1             |     return meth(obj, **kw)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
pgadmin4_1             |     include_foreign_key_constraints=include_foreign_key_constraints
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
pgadmin4_1             |     return meth(self, multiparams, params)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
pgadmin4_1             |     return connection._execute_ddl(self, multiparams, params)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
pgadmin4_1             |     compiled
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
pgadmin4_1             |     context)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
pgadmin4_1             |     exc_info
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
pgadmin4_1             |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
pgadmin4_1             |     context)
pgadmin4_1             |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
pgadmin4_1             |     cursor.execute(statement, parameters)
pgadmin4_1             | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'\nCREATE TABLE alembic_version (\n\tversion_num VARCHAR(32) NOT NULL, \n\tCONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)

```

**Comment by RichardBruskiewich** [comment]
@erasche @abretaud I'm pleased to report this morning that by the end of the day, yesterday, I was generally successful in firing up the whole dockerized gmod deployment system, following the README instructions, and configured it behind our HTTPS proxy server.

One thing I did do, however, was insert most of our previous **docker-tripal** customization, and substituted the **v3.x** branch image (rather than the master branch) to make sure everything worked (e.g. behind HTTPS, with the latest v3.x modules, etc.).  

There is one more customization I need to apply this morning which I assume should work, then my team and I will be delighted to continue our DivSeek Canada Portal work using the **dockerized-gmod-deployment** project a the core.

I suspect that we'll still have plenty of feedback to give you on the project, along various fronts, as we use it.  Meanwhile, thanks again for the quick iterations on your side to get things generally running!

**Comment by hexylena** [comment]
@RichardBruskiewich that's great news! We're glad to hear that it's working for you. It's cool to see this used in production :) If you have a URL that you can share when you're done, we're happy to mention it in the readme for this project.

If you have more questions you're welcome to [chat with us on gitter](https://gitter.im/galaxy-genome-annotation/Lobby).

@abretaud would you be comfortable that the tripal image defaults to v3.x?

**Comment by RichardBruskiewich** [comment]
We're hoping to have something to demo online by mid-January, if we can get our general act together. We'll keep you all posted.

On the documentation of the configuration of this project, you might very well wish to make cross-reference to the configuration README's of the various component projects, such as docker-tripal. I consulted these instinctively, but fresh users might benefit from being pointed to such excellent supplemental documentation (for each component).

**Comment by abretaud** [comment]
That's really great news @RichardBruskiewich! Can't wait to see a demo!
I've just merge the v3.x docker-tripal branch into master, I've kept a v2.x branch in case we want to update it later. It's rebuilding on quay.io currenlty. I'll try to update all references (and add links to the docs)
